name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # diariamente
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: edu-lopes

          # ====== MÃ‰TRICAS PRINCIPAIS ======
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo

          # ====== LINGUAGENS ======
          plugin_languages: yes
          plugin_languages_limit: 6

          # ====== STREAK ======
          plugin_streak: yes

          # ====== COMMITS ======
          plugin_lines: yes

          # ====== VISUAL ======
          config_display: large
          config_output: svg
